### ISSUE TITLE
Refreshing the time and the weather sometimes causes a contour to appear on the widget's background

### ISSUE THREAD

**Issue by balazs-kis** [BalazsKis/media-center#6]
![capture](https://cloud.githubusercontent.com/assets/19716399/26142403/a0ec87a0-3ae0-11e7-9965-c172705fa513.PNG)

**Comment by koccs** [comment]
It was investigated with new div over the time widget and still persists. It seems it is a rendering bug built in chrome engine.
![image](https://cloud.githubusercontent.com/assets/28656450/26169152/ed3ee218-3b3c-11e7-8366-61100355b71c.png)
